[package]
name = "validate-git-blame-ignore-revs"
description = "Validate a .git-blame-ignore-revs file"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
regex = "1.11.2"

[dev-dependencies]
tempfile = "3.21.0"
